[phases.init]
nixPkgs = ["python311", "python311Packages.pip", "fontconfig"]

[phases.setup]
nixPkgs = ["python311"]

[phases.install]
nixPkgs = ["python311"]
cmds = ["pip install --upgrade pip", "pip install -r requirements.txt"]

[start]
cmd = "python dashboard.py"
